# Default values for prometheus-config-updator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  prometheusConfigUpdator:
    enabled: false
    googleStorage:
      enabled: true
      project: ""
      zone: ""
      bucketUrl: "" # e.g. gs://skr-prometheus-config
      configFile: "" # prometheus.yaml
      bucketViewerServiceAccountKey: "" # base64 encoded service account json key

image:
  kubectl:
    repository: linkyard/kubectl
    tag: 1.14.2
    pullPolicy: IfNotPresent
  configPuller:
    repository: google/cloud-sdk
    tag: alpine
    pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
