{{- if and .Values.global.prometheusConfigUpdator.enabled .Values.global.prometheusConfigUpdator.googleStorage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-config-updator.fullname" . }}-google-storage
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "prometheus-config-updator.name" . }}
    chart: {{ template "prometheus-config-updator.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
data:
  project: {{ .Values.global.prometheusConfigUpdator.googleStorage.project | b64enc | quote }}
  zone: {{ .Values.global.prometheusConfigUpdator.googleStorage.zone | b64enc | quote }}
  bucketUrl: {{ .Values.global.prometheusConfigUpdator.googleStorage.bucketUrl | b64enc | quote }}
  configFile: {{ .Values.global.prometheusConfigUpdator.googleStorage.configFile | b64enc | quote }}
  bucketViewerServiceAccountKey: {{ .Values.global.prometheusConfigUpdator.googleStorage.bucketViewerServiceAccountKey | quote }}
{{- end }}
